# Generated by Django 4.2.2 on 2023-06-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_link', models.URLField()),
                ('project_image', models.ImageField(upload_to='images/')),
                ('project_descp', models.TextField()),
            ],
        ),
    ]
