# Generated by Django 4.2.2 on 2023-06-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('create_project', 'Can add project'), ('remove_project', 'Can delete project')]},
        ),
    ]
