# Generated by Django 4.2.2 on 2023-07-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_date', models.DateField(null=True)),
                ('blog_image', models.ImageField(null=True, upload_to='')),
                ('blog_content', models.TextField()),
            ],
        ),
    ]
